### ISSUE TITLE
Add label elements

### ISSUE THREAD

**Issue by brothercake** [stevefaulkner/targetsize#4]
Explicitly associated `<label>` elements also count as pointer targets for the purposes of Target Size.

If the `<input>` is inside the `<label>` then the whole thing is a single target, otherwise they count as two separate targets. (But you probably don't need to check that, you could just draw two circles in either case.)

**Comment by stevefaulkner** [comment]
this was the prompt i used:

> modify the bookmarklet so that if an input has an associated label element (associated either by use of for and id attributes or by nesting of inputs in the label element) the center is calculated as the center of the input and its associated label element
